CHANGELOG.md
workers/ohsome_quality_analyst/base/indicator.py
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_tags_ratio.json
workers/tests/integrationtests/test_indicator_tags_ratio.py

Check for invalid indicator layer combination during initialization of indicator objects

---

CHANGELOG.md
workers/ohsome_quality_analyst/api.py
workers/ohsome_quality_analyst/indicators/ghs_pop_comparison_buildings/indicator.py
workers/ohsome_quality_analyst/indicators/ghs_pop_comparison_roads/indicator.py
workers/ohsome_quality_analyst/indicators/last_edit/indicator.py
workers/ohsome_quality_analyst/indicators/mapping_saturation/sigmoid_curve.py
workers/ohsome_quality_analyst/indicators/poi_density/indicator.py
workers/ohsome_quality_analyst/indicators/tags_ratio/indicator.py
workers/poetry.lock
workers/pyproject.toml
workers/setup.cfg
workers/tests/integrationtests/test_cli.py
workers/tests/integrationtests/test_indicator_mapping_saturation.py
workers/tests/integrationtests/test_oqt.py
workers/tests/unittests/test_api.py
workers/tests/unittests/test_cli.py

* Add flake8-naming package as dev dependency.
* Add configuration to ignore flake8-naming warnings for Python files in `indicators/mapping-saturation/`
- pep8-naming
- ~~[ ] My code follows the [style guide](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#pre-commit) before committing~~ 
- ~~[ ] I have commented my code~~ 
- ~~[ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-analyst/blob/main/docs/development_setup.md#tests)~~

Add flake8 plugin pep8-naming as development dependency

---

CHANGELOG.md
workers/ohsome_quality_analyst/base/report.py
workers/ohsome_quality_analyst/reports/jrc_requirements/report.py
workers/ohsome_quality_analyst/reports/map_action_poc/report.py
workers/ohsome_quality_analyst/reports/remote_mapping_level_one/report.py
workers/ohsome_quality_analyst/reports/simple_report/report.py
workers/ohsome_quality_analyst/reports/sketchmap_fitness/report.py

Implement combine_indicators() as Concrete Method of the Base Blass `Report`.
This provides a default method for combining indicators to all reports.
This will also reduce code duplication across those report (child classes).
Closes #32

Implement combine_indicators() as Concrete Method

---

workers/ohsome_quality_analyst/cli_opts.py
workers/tests/unittests/test_cli.py

This bug has been caused due to missing name attribute of custom click
type class (feature_id_field)
Closes #58

Fix CLI help bug

---

docs/troubleshooting.md

Added a workaround to the troubleshooting document for failing DB builts on Windows. Suggests to use the Ubuntu command line for Windows and Notepad++
- ~~My code follows the [style guide](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#pre-commit) before committing~~
- ~~I have commented my code~~
- ~~I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-analyst/blob/main/docs/development_setup.md#tests)~~
- ~~I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CHANGELOG.md)~~

Added workaround for failing DB-build using Windows to troubleshooting doc

---

CHANGELOG.md
workers/ohsome_quality_analyst/utils/definitions.py

When a test fails PyTest will print out logs of log level Debug. This leads to a cluttered terminal screen since alot of debug messages from third party libraries will be printed out to stdout.
This PR will set the log level to INFO to reduce messages to stdout.

Set log level of PyTest to INFO

---

CHANGELOG.md
Jenkinsfile
docs/development_setup.md
workers/tests/integrationtests/utils.py

This change allows to configure if the tests never query the ohsome API but fail, or recreate all VCR cassettes, see https://vcrpy.readthedocs.io/en/latest/usage.html#record-modesv
None
None

make VCR mode configurable

---

CHANGELOG.md
workers/ohsome_quality_analyst/base/indicator.py
workers/ohsome_quality_analyst/indicators/ghs_pop_comparison_buildings/indicator.py
workers/ohsome_quality_analyst/indicators/ghs_pop_comparison_roads/indicator.py
workers/ohsome_quality_analyst/indicators/last_edit/indicator.py
workers/ohsome_quality_analyst/indicators/mapping_saturation/indicator.py
workers/ohsome_quality_analyst/indicators/poi_density/indicator.py
workers/ohsome_quality_analyst/indicators/tags_ratio/indicator.py
workers/ohsome_quality_analyst/oqt.py

Change return type from bool to None for indicator for functions: preprocess, calculate, create_figure
Closes #
-

Change return type from bool to None for indicator

---

Jenkinsfile
sonar-project.properties

* The analysis done by the sonar scanner is currently missing the project version. This PR adds the missing version. More information: https://sonarcloud.io/documentation/improving/new-code/
* The supported Python versions weren't specified for the sonar scanner. More information: https://sonarcloud.io/documentation/advanced-setup/languages/python/

Jenkins: add project version and python version to sonar scanner analysis

---

website/website/assets/js/map-en.js
website/website/index.html

Removes a unused section of code: As far as I can see the map never has a layer control, so the onclick handler can never be triggered.
And as a consequence, remove the jQuery library, which is AFAICS no where else used in the project. Btw, jQuery was included twice in two slightly different versions from two different CDNs. :see_no_evil:

drop unused UI code, and dependency to jQuery completely

---

CHANGELOG.md
website/website/assets/js/map-en.js
website/website/index.html

Solved 2 bugs, the first one being #122, which was caused by using on click on a select instead of on change, and the second one being caused by async loading dependencies for later js which is risky on devices with varying speeds.
Closes #122

fixed 2 bugs for mobile

---

CHANGELOG.md
database/scripts/queries/get_results_as_geojson.sql
workers/ohsome_quality_analyst/geodatabase/client.py
workers/ohsome_quality_analyst/geodatabase/create_results_table.sql
workers/ohsome_quality_analyst/geodatabase/load_results.sql
workers/ohsome_quality_analyst/geodatabase/save_results.sql
workers/tests/integrationtests/test_geodatabase.py

Extend database schema with one additional attribute of type JSON.
During saving indicator attribute to database, dump the
indicator.as_feature() output to the database as well. The reason is to
not lose any data when saving and loading and indicator from and to the
database such as the indicator.data attribute (see issue #145).
Workflow to save and load an indicator form the database will stay the same.
This work will be helpful in solving issue #145.

 Save indicator as GeoJSON Feature to DB

---

workers/ohsome_quality_analyst/indicators/mapping_saturation/indicator.py
workers/setup.cfg

Clean-up code of mapping saturation indicator
- Fix var naming causing flake8 pep8 naming errors
- Remove panda usage because it is not needed
- Use multiple object attributes instead of one dict for all variables
- Reduce code by deleting unnecessary code or compressing into fewer
statements

Clean-up code of the Mapping Saturation indicator

---

workers/ohsome_quality_analyst/api/api.py
workers/tests/integrationtests/test_api.py

Since commit c736f10 the response of the API endpoint `/regions` has not been a valid GeoJSON anymore. This broke the display of regions on the website if there where not locally (in the website directory) available.

Fix API invalid geojson response of `/regions`

---

CHANGELOG.md
workers/tests/integrationtests/api_response_schema.py
workers/tests/integrationtests/test_api.py
workers/tests/integrationtests/test_api_indicator.py
workers/tests/integrationtests/test_api_indicator_geojson_io.py
workers/tests/integrationtests/test_api_report.py
workers/tests/integrationtests/test_api_report_geojson_io.py

Add test cases covering the content of GeoJSON properties.
Improve API response schemata by using less logic to create the
schemata.
Closes #131

Add and improve tests for API

---

.pre-commit-config.yaml
workers/poetry.lock
workers/pyproject.toml

In particular isort, Black and flake8 are updated in
`pyproject.toml` and `.pre-commit-config.yaml`.
Those versions are fixed to ensure compatibility between Poetry and
pre-commit.
Updated depedencies:
- isort
- pep8-naming
- flake8
- black
- pre-commit

Update development dependencies

---

CHANGELOG.md
workers/ohsome_quality_analyst/geodatabase/client.py
workers/ohsome_quality_analyst/utils/helper.py
workers/tests/integrationtests/test_geodatabase.py
workers/tests/unittests/test_helper.py

Now loading an indicator from the DB will not only load the indicator results but also
any arbitrary data (the indicator attributes) which has been calculated
and saved to the DB as JSON.
Closes #145

Load indicator from DB will load data attributes

---

CHANGELOG.md
website/website/assets/js/map-en.js
workers/ohsome_quality_analyst/api/api.py
workers/ohsome_quality_analyst/geodatabase/client.py
workers/tests/integrationtests/test_api.py
workers/tests/integrationtests/test_geodatabase.py

- Update API endpoint for fetching regions in website source code.
- Rearrange CHANGELOG to reflect Breaking Changes.
- API endpoint regions will return a JSON array of key-value maps instead of an nested array. Values are names and identifiers of the regions.

Change output format of the API endpoint `/regions` to a JSON Array of key-value maps

---

workers/ohsome_quality_analyst/indicators/currentness/indicator.py
workers/ohsome_quality_analyst/indicators/currentness/metadata.yaml

Correct grammar and variable names for curentness indicator.
Closes #
-

Currentness correction

---

workers/poetry.lock
workers/pyproject.toml

On a system with Python 3.10 installed following error will be raised after installation of OQT is done as described in docs (`poetry install`).
```
oqt --help
Traceback (most recent call last):
File "/home/matthias/.cache/pypoetry/virtualenvs/ohsome-quality-analyst-n8AqUv-Z-py3.10/bin/oqt", line 2, in <module>
from ohsome_quality_analyst.cli.cli import cli
File "/home/matthias/work/oqt-prod/workers/ohsome_quality_analyst/cli/cli.py", line 9, in <module>
from ohsome_quality_analyst import oqt
File "/home/matthias/work/oqt-prod/workers/ohsome_quality_analyst/oqt.py", line 9, in <module>
from asyncpg.exceptions import UndefinedTableError
File "/home/matthias/.cache/pypoetry/virtualenvs/ohsome-quality-analyst-n8AqUv-Z-py3.10/lib64/python3.10/site-packages/asyncpg/__init__.py", line 8, in …
```

Update deps and bump version of asyncpg

---

CHANGELOG.md
workers/ohsome_quality_analyst/utils/definitions.py

Layer definition "IDEAL-VGI Land Use and Land Cover" has been a valid
layer in combination with the Mapping Saturation indicator.
But often time the area of the land-use gets smaller over time instead
of bigger, which makes it not suitable for the Mapping Saturation.
Beside that the Layer has not been used in any Report.
~- [ ] My code follows the [style guide](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#pre-commit) before committing~

Remove layer definition "ideal_vgi_lulc"

---

docs/development_setup.md

Remove `--no-cache` of docker-compose up command.
This flag works no longer. An alterntive is to use `docker-compose build` first and the run `docker-compose up`.

Improvements to dev docs (minor)

---

workers/ohsome_quality_analyst/base/indicator.py
workers/ohsome_quality_analyst/base/report.py
workers/ohsome_quality_analyst/geodatabase/client.py
workers/ohsome_quality_analyst/oqt.py
workers/ohsome_quality_analyst/utils/helper.py
workers/tests/integrationtests/test_base_indicator.py
workers/tests/unittests/test_helper.py

Supported nested lists for func `flatten_dict`.
Make flatten of Feature Properties optional.
This will make unflatten function obsolete. This function has been used
to "unflatten" the Feature Properties after loading them from the
database. Now the Feature will be stored to the database in "unflattend"
form.
Remove obsolete function `unflatten_dict`.
- ~~[ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CHANGELOG.md)~~
- Should it be possible to make an request to the API for an unflattend response?

Make flatten of Feature Properties optional

---

workers/ohsome_quality_analyst/base/indicator.py
workers/ohsome_quality_analyst/indicators/mapping_saturation/indicator.py
workers/ohsome_quality_analyst/ohsome/layer_definitions.yaml
workers/ohsome_quality_analyst/utils/definitions.py
workers/tests/unittests/test_load_layers.py

Reverse #221, rename layer and return result description in the case that the indicator could not been calculated (instead of raising an error which will not be handed down to the API).
- Closes #257 
- Addresses part of #259 
- ~~[ ] I have commented my code~~
- ~~[ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-analyst/blob/main/docs/development_setup.md#tests)~~
- ~~[ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CHANGELOG.md)~~

Reverse #221, rename layer and return result description

---

CHANGELOG.md
workers/ohsome_quality_analyst/cli/cli.py
workers/ohsome_quality_analyst/oqt.py
workers/ohsome_quality_analyst/utils/definitions.py
workers/tests/integrationtests/test_oqt.py
workers/tests/unittests/test_cli.py
workers/tests/unittests/test_definitions.py

- Support any dataset, not just "regions" for the CLI function `create_all_indicators`.
- Fix concurrent execution of `create_all_indicators` using async and semaphores. (See description of the problem below)
- Add support of single indicator and/or single layer to the CLI command `create_all_indicators`.
Somehow during creation of the async tasks they got duplicated (same function with same parameter values), which resulted in creating the same indicator multiply times. This ended quickly in a write error to the database.
```
Usage: oqt create-all-indicators [OPTIONS]
Create all Indicators for all features of the given dataset.
The default is to create all Indicator/Layer combinations for all features
of the given dataset. This can be restricted to one Indicator type and/or
one Layer …
```

Fix and improve CLI command `create_all_indicators`

---

CHANGELOG.md
workers/ohsome_quality_analyst/indicators/ghs_pop_comparison_buildings/indicator.py
workers/ohsome_quality_analyst/indicators/ghs_pop_comparison_roads/indicator.py
workers/tests/integrationtests/test_indicator_ghs_pop_comparison_buildings.py
workers/tests/integrationtests/test_indicator_ghs_pop_comparison_roads.py

Indicators based on GHS_POP raster are now calculated with rasterstats and from raster on the disk instead of the database.
Closes #267

GHS_POP indicators use raster from disc

---

docs/examples/minimal-example.html

This PR adds an example how the new `includeHtml` parameter can be used with JavaScript. This example is not meant for direct use, but as showcase how easy it can be.
None
None

Add minimal example using the new HTML output feature

---

CHANGELOG.md
workers/ohsome_quality_analyst/api/api.py

Add missing error handling of `RasterDatasetUndefinedError` and `RasterDatasetNotFoundError` to the API.
Those errors have been introduced in PR #227. By adding those error to the error handling of the API they will be reported back to the user in form of a API response.

Add missing error handling to the API

---

CHANGELOG.md
docs/api.md
workers/ohsome_quality_analyst/api/api.py
workers/ohsome_quality_analyst/api/request_models.py
workers/tests/integrationtests/test_api.py

Improve API documentation and examples.
Now Indicator and Report endpoints have their own "group" in the Swagger interface. Also both link to the external API documentation. See in comments below for a screenshot.
Closes #295 
Closes #297
Closes #294

Improve API documentation and examples

---

docs/development_setup.md

Remove GDAL as dependency from docs.
GDAL has been falsely added as dependency.
- None
- None

Remove GDAL as dependency from docs

---

CHANGELOG.md
docs/api.md
workers/ohsome_quality_analyst/api/api.py
workers/ohsome_quality_analyst/api/request_models.py
workers/ohsome_quality_analyst/base/report.py
workers/ohsome_quality_analyst/oqt.py
workers/tests/integrationtests/test_api_indicator.py
workers/tests/integrationtests/test_api_report.py
workers/tests/integrationtests/test_base_report.py
workers/tests/unittests/test_api.py
workers/tests/unittests/test_api_request_models.py

Make flatten of GeoJSON properties of Indicators and Reports optional.
Continue work of #247 
Closes #281 
- None

 Add 'flatten' parameter to API request

---

CHANGELOG.md
workers/ohsome_quality_analyst/oqt.py
workers/ohsome_quality_analyst/utils/helper.py

Make calculation of an Indicator for a FeatureCollection or for a Report asynchronous
Closes #305 
- None
- Not sure. Are more test needed?

Make calculation of an Indicator for a FeatureCollection or for a Report asynchronous

---

workers/ohsome_quality_analyst/ohsome/client.py

`groupByObject` value can also be int, not just str.
None
- None

fix validation of groupBy responses of ohsome API

---

workers/ohsome_quality_analyst/geodatabase/client.py
workers/ohsome_quality_analyst/geodatabase/select_shdi.sql
workers/tests/integrationtests/test_geodatabase.py

previously `get_shdi` worked only for one feature (one geometry). This PR adds support for FeatureCollections (multiple geoms). This is useful when requesting SHDI for multiple hex-cells for example.
None
- None

support FeatureCollections for func `get_shdi`

---

CHANGELOG.md
workers/ohsome_quality_analyst/oqt.py
workers/tests/integrationtests/test_oqt.py

Only enforce size limit on input AOI if ohsome API needs to be queried.
If OSM data is provided through a request with a custom Layer object
disable the size restriction.
None
- None

Disable size limit for requests with data

---

workers/ohsome_quality_analyst/raster/client.py
workers/ohsome_quality_analyst/utils/definitions.py

Set nodata value of rasters explicitly. This avoids cluttering terminal with UserWarnings of the module `rasterstats`.
```
.cache/pypoetry/virtualenvs/ohsome-quality-analyst-JhxvPu0L-py3.9/lib/python3.9/site-packages/rasterstats/io.py:313: UserWarning: Setting nodata to -999; specify nodata explicitly
warnings.warn("Setting nodata to -999; specify nodata explicitly")
```
Closes #331 
- None

set nodata value of rasters explicitly

---

workers/ohsome_quality_analyst/base/report.py

Check added that report label is "green" if all indicators are also green. Undefined indicators are included in the report value with 0.0.
Closes #262 and #263 
-

Improve report results

---

CHANGELOG.md
workers/ohsome_quality_analyst/api/request_models.py
workers/ohsome_quality_analyst/base/indicator.py
workers/ohsome_quality_analyst/base/report.py
workers/ohsome_quality_analyst/geodatabase/client.py
workers/ohsome_quality_analyst/oqt.py
workers/tests/integrationtests/test_api_indicator.py
workers/tests/integrationtests/test_base_indicator.py
workers/tests/integrationtests/test_base_report.py
workers/tests/integrationtests/test_indicator_mapping_saturation.py
workers/tests/unittests/test_api_request_models.py

make inclusion of indicator data in response optional
Closes #359 
- None

make inclusion of indicator data in response optional

---

CHANGELOG.md
workers/ohsome_quality_analyst/api/api.py
workers/tests/integrationtests/test_api.py

BREAKING CHANGE: Rename endpoints for listing of indicator,
report, layer, dataset and fid-field names.
Closes https://github.com/GIScience/ohsome-quality-analyst/issues/162
- None

refactor(api)!: rename endpoints

---

CHANGELOG.md
workers/ohsome_quality_analyst/indicators/building_completeness/indicator.py

figure did not display completeness ratio over 100%.
Now figure figure will display completeness ratio up to 150%.
None
- None

fix: building completeness figure

---

CHANGELOG.md
workers/ohsome_quality_analyst/definitions.py
workers/ohsome_quality_analyst/ohsome/layer_definitions.yaml
workers/ohsome_quality_analyst/reports/multilevel_mapping_saturation/report.py

Rename layer ideal_vgi_infrastructure to basic_infrastructure.
Closes #259
- None

rename layer ideal_vgi_infrastructure to basic_infrastructure

---

workers/Dockerfile.continuous-integration

Node version has to be ≥ 14 for sonar-scanner, received directly from nodesource.com
None
None (in CI Node ≥ 14)
Please check all finished tasks. If some tasks do not apply to your PR, please cross their text out (by using `~...~`) and remove their …

Temporary fix for sonar-scanner node version

---

CHANGELOG.md
workers/ohsome_quality_analyst/ohsome/layer_definitions.yaml

Rename duplicated layer name `Major Roads` to `Major Roads Count` and `Major Roads Length`. Results are stored in database using the layer name as part of the primary key.

fix: change layer names to avoid duplication

---

database/Dockerfile.development

Remove pdgd repos since Postgres 10 isn't supported by them anymore.
None
None

Database Dockerfile: Remove pdgd repos

---

docs/development_setup.md
workers/poetry.lock
workers/pyproject.toml

Closes #463
Closes #451 
Closes #441 
- Python requirement: >=3.8
- building-completeness-indicator bump to 0.1.0rc4 (bump required python version to <=3.11)
- Updating pyyaml (5.4.1 -> 6.0)
- Updating fastapi (0.68.2 -> 0.86.0)
- Updating uvicorn (0.17.6 -> 0.20.0)

build(deps): update

---

workers/ohsome_quality_analyst/ohsome/layer_definitions.yaml

There are two identical layers called supermarkets.

fix: delete duplicated layer supermarkets

---

CHANGELOG.md
workers/ohsome_quality_analyst/api/request_models.py
workers/ohsome_quality_analyst/cli/cli.py
workers/ohsome_quality_analyst/oqt.py
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_indicator.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_indicator_geojson_io.yaml
workers/tests/integrationtests/test_api_geojson_io.py
workers/tests/integrationtests/test_api_indicator.py
workers/tests/integrationtests/test_api_indicator_geojson_io.py
workers/tests/integrationtests/test_oqt.py
workers/tests/integrationtests/test_oqt_geojson_io.py
workers/tests/unittests/test_api_request_models.py

BREAKING CHANGE: Rename API parameter `layerKey` and `layer` to `topic`
Related Issue #502  
Closes  #491

refactor(api)!: rename layerKey and layer to topic

---

CHANGELOG.md
workers/ohsome_quality_analyst/ohsome/client.py

The metadata requests to the ohsome API got a timeout error, because the default `httpx` timeout was used.
Closes #537
None

fix: add timeout for ohsome API metadata requests

---

CHANGELOG.md
docs/api.md
workers/ohsome_quality_analyst/definitions.py
workers/tests/integrationtests/api/conftest.py
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_indicator.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_indicator_geojson_io.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_report.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_report_geojson_io.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_geojson_io.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_report.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_report_geojson_io.yaml
workers/tests/unittests/test_api.py

attribution URL was wrong and was replaced in this PR
None
None

fix(api): replace attribution URL path

---

CHANGELOG.md
workers/ohsome_quality_analyst/api/api.py
workers/ohsome_quality_analyst/api/request_models.py
workers/ohsome_quality_analyst/api/response_models.py
workers/ohsome_quality_analyst/definitions.py
workers/ohsome_quality_analyst/indicators/attribute_completeness/metadata.yaml
workers/ohsome_quality_analyst/indicators/building_completeness/metadata.yaml
workers/ohsome_quality_analyst/indicators/currentness/metadata.yaml
workers/ohsome_quality_analyst/indicators/mapping_saturation/metadata.yaml
workers/ohsome_quality_analyst/indicators/minimal/metadata.yaml
workers/ohsome_quality_analyst/indicators/models.py
workers/ohsome_quality_analyst/indicators/poi_density/metadata.yaml
workers/ohsome_quality_analyst/reports/building_report/metadata.yaml
workers/ohsome_quality_analyst/reports/food_related_report/metadata.yaml
workers/ohsome_quality_analyst/reports/map_action_poc/metadata.yaml
workers/ohsome_quality_analyst/reports/minimal/metadata.yaml
workers/ohsome_quality_analyst/reports/models.py
workers/ohsome_quality_analyst/reports/multilevel_currentness/metadata.yaml
workers/ohsome_quality_analyst/reports/multilevel_mapping_saturation/metadata.yaml
workers/ohsome_quality_analyst/reports/road_report/metadata.yaml
workers/ohsome_quality_analyst/reports/sketchmap_fitness/metadata.yaml
workers/tests/conftest.py
workers/tests/integrationtests/api/conftest.py
workers/tests/integrationtests/api/test_metadata.py
workers/tests/integrationtests/api/test_metadata_indicators.py
workers/tests/integrationtests/api/test_metadata_reports.py
workers/tests/integrationtests/api/test_metadata_topics.py
workers/tests/unittests/api/test_response_models.py
workers/tests/unittests/test_definitions.py

This PR introduces:
- the `/metadata` endpoint containing all metadata from `/metadata/{topics,indicators,reports}`
- the `/metadata/reports` endpoint
- limit metadata endpoints by projects
- the use of the `core` project as default for metadata requests
- assigns indicators and reports to projects
- Related to #485 
- Closes #495
None

Add remaining metadata endpoints

---

workers/ohsome_quality_analyst/topics/presets.yaml

add mapping-saturation to building_area topic
None
None

feat(topic): add mapping-saturation to building_area topic

---

database/development/Dockerfile
workers/Dockerfile.continuous-integration
workers/tests/integrationtests/test_indicator_building_completeness.py

Postgres 15 and Postgis 3.3 are used on the production server in the future. Therefore we update our docker dev setup.
Closes #148 
- Postgres 15
- Postgis 3.3

Update postgres and postgis

---

CHANGELOG.md
workers/ohsome_quality_analyst/api/api.py
workers/ohsome_quality_analyst/utils/exceptions.py

Homogenize API response schema for errors.
Default JSON error like ValidationErrors by Pydantic/FastAPI:
```json
{
"detail": [
{
"loc": [
"path",
"item_id"
],
"msg": "value is not a valid integer",
"type": "type_error.integer"
}
]
}
```
The PR changes the response schema for errors in OQT to:
```json
{
"apiVersion": __version__,
"type": "type_error.integer"
"detail": [
{
"loc": [
"path",
"item_id"
],
"msg": "value is not a valid integer",
"type": "type_error.integer"
}
]
}
```
Whereas  `["detail"]["loc"]` and `["detail"]["type"]` are optional and only in use for Request Validation Errors raised by Pydantic/FastAPI.
Closes #
-

feat(api): homogenize response schema for errors

---

workers/tests/integrationtests/indicators/test_building_completeness.py

Fix minor bug in building completeness tests. See also [sonarcloud issue](https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&types=BUG&id=ohsome-quality-analyst&open=AYgKVp3U0R3R5X1AIBUr).
None
None

fix: building completeness test bug

---

CHANGELOG.md
workers/ohsome_quality_analyst/api/api.py

In deployment we are using a [Proxy](https://fastapi.tiangolo.com/advanced/behind-a-proxy/#setting-the-root_path-in-the-fastapi-app). Therefore we need to make sure all our paths are prepended with this proxy path. This is automatically done for the API, but not for swagger. This PR fixes this issue.
None
None

fix(swagger): root_path is used for static files

---

CHANGELOG.md
docs/api.md
workers/ohsome_quality_analyst/indicators/base.py
workers/ohsome_quality_analyst/indicators/models.py
workers/ohsome_quality_analyst/reports/base.py
workers/ohsome_quality_analyst/reports/models.py
workers/tests/integrationtests/api/response_schema.py
workers/tests/integrationtests/api/test_indicators.py
workers/tests/integrationtests/api/test_report.py

- fix(API): use camel-case for all JSON keys in indicator/report results
- fix(API): use OQT/OSM in JSON keys in indicator/report results
None
None

Refactor result keys

---

CHANGELOG.md
workers/ohsome_quality_analyst/api/api.py
workers/tests/integrationtests/api/test_indicators.py

JSON response for `/indicators/{key}` now uses `results` instead of `result` on the top layer, since the value is an array with potentially multiple results.
None
None

chore(api): use plural in JSON indicator response

---

CHANGELOG.md
workers/ohsome_quality_analyst/geodatabase/client.py
workers/ohsome_quality_analyst/indicators/density/indicator.py
workers/ohsome_quality_analyst/oqt.py
workers/ohsome_quality_analyst/utils/exceptions.py
workers/ohsome_quality_analyst/utils/helper_geo.py
workers/ohsome_quality_analyst/utils/validators.py
workers/tests/integrationtests/test_geodatabase.py
workers/tests/integrationtests/test_oqt.py
workers/tests/unittests/test_helper_geo.py
workers/tests/unittests/test_validators.py

refactor: calculate geom area with pyproj instead of using PostGIS

refactor: calculate geom area with pyproj

---

CHANGELOG.md
workers/ohsome_quality_analyst/api/api.py
workers/tests/integrationtests/api/test_indicator_geojson_io.py
workers/tests/integrationtests/api/test_indicators.py
workers/tests/integrationtests/api/test_indicators_mapping_saturation_data.py

computing mapping-saturation indicator for given data is now a separate endpoint.
Closes #594

refactor(api)!: computing mapping-saturation indicator for given data is now a separate endpoint

---

CHANGELOG.md
ohsome_quality_analyst/api/api.py
ohsome_quality_analyst/api/request_models.py
ohsome_quality_analyst/oqt.py
tests/integrationtests/api/test_indicators.py
tests/integrationtests/test_oqt.py
tests/unittests/api/test_request_models.py

feat(api): add `includeFigure` parameter to `/indicators` endpoint. Default is `True`.
Closes #617 
- None

feat(api): add `includeFigure` parameter to `/indicators` endpoint.

---

CHANGELOG.md
ohsome_quality_api/geodatabase/client.py
ohsome_quality_api/geodatabase/get_coverage_intersection.sql
ohsome_quality_api/indicators/building_comparison/indicator.py
tests/integrationtests/fixtures/vcr_cassettes/indicators/test_building_comparison.yaml
tests/integrationtests/indicators/test_building_comparison.py
tests/integrationtests/test_geodatabase.py
tests/unittests/test_indicators_definitions.py

Closes #733 
Closes #731 
Closes #735
Closes #732
Closes #737 
Closes #734 
-

building-comparison: fix checks and result description

---

Dockerfile
Jenkinsfile
pipeline_config.groovy

The Jenkinsfile used on the old Jenkins server did not work on the new one due to differences in the setup, e.g. the old Jenkins being in a docker container itself and the new one running directly in the OS. The UID and GID for the oqapi user inside the Docker container and the jenkins user in the jenkins workspace had to be matched and we had to mount the jenkins tools directory into the docker container to user sonar scanner.
~~- [ ] I have updated my branch to `main` (e.g. through `git rebase main`)~~
~~- [ ] My code follows the [style guide](https://github.com/GIScience/ohsome-quality-api/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-api/blob/main/CONTRIBUTING.md#pre-commit) before committing~~
~~- [ ] I have …

Updating Jenkinsfile for new Jenkins server

---

CHANGELOG.md
ohsome_quality_api/indicators/building_comparison/indicator.py
ohsome_quality_api/indicators/building_comparison/sources.yaml
tests/integrationtests/indicators/test_building_comparison.py

Adding the release date of EUBUCCU and OSM timestamp to plot. Furthermore, laying groundwork to use same infrastructure for future further datasets
Closes #750
-

Adding release date of EUBUCCU and OSM timestamp to plot

---

.pre-commit-config.yaml
CHANGELOG.md
ohsome_quality_api/indicators/building_comparison/indicator.py
poetry.lock
pyproject.toml

Cache request to eubucco db.
Closes #753
- async-lru

feat(building-comparison): cache request to db

---

ohsome_quality_api/indicators/building_comparison/metadata.yaml

Avoid folling case:
> The building area of OSM is 96.66% of that of the reference data. OSM has equal or more building area than the reference data.

fix(building-comparison): label description

---

ohsome_quality_api/indicators/building_comparison/datasets.yaml
ohsome_quality_api/indicators/building_comparison/indicator.py
tests/integrationtests/indicators/test_building_comparison.py
tests/unittests/test_indicators_definitions.py

fixes the bug described in issue #771 by using the feature directly instead of trying to create one from a string
Closes #771 
Closes #773 
- None
- ~[ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-api/blob/main/CHANGELOG.md)~

feat(building-comparison): bug fixing after multiple reference datasets change

---

CHANGELOG.md
ohsome_quality_api/api/request_models.py

use Pydantic model from the `geojson-pydantic` library as request model for `bpolys`.
Closes #704 
- `pydantic-geojson`

feat(api): use `geojson-pydantic` as request model

---

CHANGELOG.md
ohsome_quality_api/indicators/base.py
tests/integrationtests/test_base_indicator.py

Fix wrong creation of global coverage in the base indicator.
Closes #821
~- [ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-api/blob/main/docs/development_setup.md#tests)~

fix: global coverage geojson

---

CHANGELOG.md
ohsome_quality_api/api/request_models.py
regression-tests/roads_polygon_attributecompleteness.hurl
regression-tests/roads_polygon_mappingsaturation.hurl
tests/integrationtests/api/conftest.py

Add missing properties dict to example GeoJSON.
Closes #831
~- [ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-api/blob/main/docs/development_setup.md#tests)~

fix: invalid example GeoJSON in swagger

---

CHANGELOG.md
ohsome_quality_api/api/request_models.py
ohsome_quality_api/indicators/attribute_completeness/indicator.py
ohsome_quality_api/indicators/base.py
ohsome_quality_api/indicators/indicators.yaml
ohsome_quality_api/projects/projects.yaml
ohsome_quality_api/topics/presets.yaml
regression-tests/roads_polygon_attributecompleteness.hurl
regression-tests/roads_polygon_mappingsaturation.hurl
tests/integrationtests/api/conftest.py
tests/integrationtests/test_base_indicator.py

Skip figure creation if calculation could not be made and add to description that no elements are present.
Closes #829
~- [ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-api/blob/main/docs/development_setup.md#tests)~

attribute-completeness: do not create figure if no objects are present

---

scripts/functions.sh
scripts/release.sh

* improved release script
* make it compatible macOS and Linux
None
None
~- [ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-api/blob/main/docs/development_setup.md#tests)~

improve release script for macOS and Linux compatibility

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

This PR aims at improving the PR template by mentioning the maintenance of hurl tests and improving wording regarding merging.
Closes #860 
- ~I have commented my code~
- ~I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-api/blob/main/docs/development_setup.md#tests)~

mention hurl test maintenance and improve mergeability wording

---

CHANGELOG.md
ohsome_quality_api/__init__.py
pyproject.toml
scripts/release.sh

This PR is used for the Oqapi release process.

release new version 1.8.2

---

ohsome_quality_api/utils/helper.py
tests/unittests/test_helper.py

refactor: address deprecation warning
pkgutil.get_loader(module_or_name) is deprecated since version 3.12,
will be removed in version 3.14: Use importlib.util.find_spec() instead.
importlib.util.find_spec() has been added in Python version 3.4.
test: rewrite unittests to by pytests and remove unused function
Closes None
- None

Address deprication warning

---

poetry.lock
pyproject.toml

Add pytest-xdist to send tests to multiple CPUs and use pytest-sugar to make output more readable
- pytest-xdist
- pytest-sugar

test: add pytest-xdist to send tests to multiple CPUs
