GIScience/ohsome-quality-api

Jenkinsfile
README.md
sonar-project.properties
workers/Dockerfile
workers/Dockerfile.continuous-integration
workers/poetry.lock
workers/pyproject.toml

This PR integrates SonarCloud and test coverage into our continuous integration. Jenkins pushes the results to sonarcloud.io.
None
- pytest-cov

Integrate sonarcloud

---

sonar-project.properties

Minor bugfix: fix wrong project name on sonarcloud.io.

sonar: fix project name

---

sonar-project.properties

Add exclusions for test coverage to ensure the sonarcloud.io metrics only include files that should be covered by the tests.
None
None

add test coverage config to sonar properties

---

workers/ohsome_quality_analyst/api.py

Remove unused function

---

workers/ohsome_quality_analyst/indicators/mapping_saturation/indicator.py

Minor improvements to code quality to the Mapping Saturation indicator.

Minor improvements to code quality

---

CHANGELOG.md

Rearrange and tidy-up Changelog for the next release

Rearrange Changelog

---

CHANGELOG.md

rearrange changes to other topics

---

CHANGELOG.md
workers/ohsome_quality_analyst/ohsome/client.py
workers/ohsome_quality_analyst/utils/definitions.py
workers/tests/unittests/test_ohsome_client.py

set user-agent specific for OQT

---

workers/ohsome_quality_analyst/cli.py
workers/ohsome_quality_analyst/oqt.py

Improve logging

---

CHANGELOG.md
workers/ohsome_quality_analyst/indicators/last_edit/indicator.py
workers/ohsome_quality_analyst/indicators/last_edit/metadata.yaml
workers/ohsome_quality_analyst/indicators/mapping_saturation/metadata.yaml
workers/ohsome_quality_analyst/indicators/poi_density/metadata.yaml

- ~[] I have commented my code~
- [] ~I have added sufficient unit and inntegration [tests](https://github.com/GIScience/ohsome-quality-analyst/blob/main/docs/development_setup.md#tests)~

Minor improvements to the metadata and docstrings of indicators

---

CHANGELOG.md
workers/ohsome_quality_analyst/cli.py
workers/ohsome_quality_analyst/utils/helper.py

Fix error raising while serializing JSON due NaN

---

Jenkinsfile

Jenkinsfile: add missing space for sonar-scanner

---

workers/tests/unittests/test_api.py
workers/tests/unittests/test_ohsome_client.py

see https://sonarcloud.io/project/issues?id=ohsome-quality-analyst&open=AXsqXZ8pLq0hvUfTBdAr&resolved=false&sinceLeakPeriod=true&types=BUG

ignore “Bug” raised by SonarCloud

---

CHANGELOG.md
docs/api.md

Add details on API response changes to CHANGELOG

---

workers/ohsome_quality_analyst/reports/simple_report/metadata.yaml

remove unnecessary quoting in simple report metadata
None
None
~|- [ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CHANGELOG.md)~

remove unnecessary quoting in simple report metadata

---

workers/tests/integrationtests/fixtures/vcr_cassettes/test_cli.json
workers/tests/integrationtests/test_api.py
workers/tests/integrationtests/test_cli.py

Add CLI-tests for list functions and rename the API-tests so that they match the function names.

Add cli-tests for list functions

---

CHANGELOG.md
workers/ohsome_quality_analyst/cli/cli.py
workers/tests/integrationtests/test_cli.py

The CLI output of list-regions is now in csv format for more clarity.
Closes #65 
-

Added csv output for list-regions

---

workers/ohsome_quality_analyst/base/indicator.py

This is obsolete since introduction of the property `data` for the indicator
object in PR #86.

Remove result.data attribute

---

workers/ohsome_quality_analyst/api/api.py
workers/ohsome_quality_analyst/api/request_models.py
workers/tests/integrationtests/test_api_indicator_geojson_io.py

response. The function will remove the `result.svg` key in the GeoJSON Properties.

Add function to remove result figure from API 

---

CHANGELOG.md
workers/ohsome_quality_analyst/cli/cli.py
workers/tests/integrationtests/test_geodatabase.py

Changes CSV string output of PR  #65 to a pretty printed table.
Related #65 

Change output format of CLI command `list-regions` to a pretty printed table of names and identifies

---

CHANGELOG.md
docs/api.md
workers/ohsome_quality_analyst/__init__.py
workers/pyproject.toml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_indicator.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_indicator_geojson_io.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_report.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_report_geojson_io.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_cli.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_cli_geojson_io.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_geodatabase.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_ghs_pop_comparison_buildings.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_last_edit.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_mapping_saturation.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_poi_density.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_tags_ratio.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_oqt.json

Release 0.6.0

---

workers/ohsome_quality_analyst/api/request_models.py

Fix usage of snake-case parameters by correct them to lower-camel-case.

Fix API examples

---

CHANGELOG.md
workers/ohsome_quality_analyst/__init__.py
workers/pyproject.toml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_indicator.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_indicator_geojson_io.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_report.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_report_geojson_io.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_cli.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_cli_geojson_io.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_geodatabase.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_currentness.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_ghs_pop_comparison_buildings.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_ghs_pop_comparison_roads.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_mapping_saturation.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_poi_density.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_tags_ratio.json
workers/tests/integrationtests/fixtures/vcr_cassettes/test_oqt.json

Release 0.8.0

---

workers/ohsome_quality_analyst/ohsome/layer_definitions.yaml
workers/ohsome_quality_analyst/utils/definitions.py

Reformulate Layer name and description of Layers POI and Landmarks Layers.
Also rename layer in `definitions.py`.
Address comments made to this PR after it was merged: https://github.com/GIScience/ohsome-quality-analyst/pull/246
Closes #161 
- ~~[ ] My code follows the [style guide](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#pre-commit) before committing~~
- ~~[ ] I have commented my code~~
- ~~[ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-analyst/blob/main/docs/development_setup.md#tests)~~
- ~~[ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-an …

Reformulate Layer name and description

---

workers/ohsome_quality_analyst/api/api.py
workers/tests/unittests/test_api.py

GeoJSON Feature or FeatureCollection into one more generic function.

Merge functions for removing a certain item from a

---

CHANGELOG.md

Move change description of #242 to New Feature

---

workers/tests/integrationtests/test_api_report_geojson_io.py

fix for failing tests because of missing VCR decorators

fix missing vcr decorators

---

CHANGELOG.md
workers/ohsome_quality_analyst/indicators/currentness/indicator.py
workers/ohsome_quality_analyst/indicators/ghs_pop_comparison_buildings/indicator.py
workers/ohsome_quality_analyst/indicators/ghs_pop_comparison_roads/indicator.py
workers/ohsome_quality_analyst/indicators/mapping_saturation/indicator.py
workers/ohsome_quality_analyst/indicators/poi_density/indicator.py
workers/ohsome_quality_analyst/indicators/tags_ratio/indicator.py
workers/ohsome_quality_analyst/ohsome/client.py
workers/ohsome_quality_analyst/utils/definitions.py
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_indicator_geojson_io.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_report_geojson_io.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_cli_geojson_io.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_mapping_saturation.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_ohsome_client.yaml
workers/tests/unittests/test_ohsome_client.py
workers/tests/unittests/utils.py

- Support `GroupBy/boundaries` queries when input feature (boundaries) to the ohsome client is a FeatureCollection
- Add more tests for the ohsome client
Closes #151

Add support for `GroupBy/boundaries` queries to the ohsome API client

---

workers/ohsome_quality_analyst/raster/client.py

fix transformation of coordinates where the input feature
coordinates has been transformed (change of projection) permanently
instead of just a copy of the feature
None
- None

fix transformation of coordinates

---

workers/ohsome_quality_analyst/oqt.py
workers/ohsome_quality_analyst/utils/helper.py
workers/ohsome_quality_analyst/utils/helper_asyncio.py
workers/tests/unittests/test_helper_asyncio.py

- factor out `asyncio` helper funcs to own module
- make `gather_with_semaphore` a wrapper of `gather`
- filter exceptions of `asyncio.gather` results
- ignore exceptions during create all indicators
- Closes #253 
- Closes #326
- None

Async gather exceptions

---

workers/ohsome_quality_analyst/geodatabase/select_shdi.sql
workers/ohsome_quality_analyst/indicators/building_completeness/indicator.py
workers/tests/integrationtests/test_indicator_building_completeness.py

set SHDI values for cells outside of intersection to the mean of the SHDI value of all other cells.
None
- None

set SHDI values for cells outside of intersection

---

workers/ohsome_quality_analyst/api/request_models.py

remove duplicated request parameters in example

---

CHANGELOG.md
website/website/index.html
workers/ohsome_quality_analyst/reports/multilevel_mapping_saturation/metadata.yaml
workers/ohsome_quality_analyst/reports/multilevel_mapping_saturation/report.py
workers/tests/unittests/test_multilevel_mapping_saturation.py

Create a new report Multilevel Mapping Saturation.
Closes #377 
- None

Create new report MultilevelMappingSaturation

---

CHANGELOG.md
workers/ohsome_quality_analyst/reports/minimal/metadata.yaml
workers/ohsome_quality_analyst/reports/minimal/report.py
workers/tests/integrationtests/test_api_geojson_io.py
workers/tests/integrationtests/test_api_report.py
workers/tests/integrationtests/test_api_report_geojson_io.py
workers/tests/integrationtests/test_base_report.py
workers/tests/integrationtests/test_cli.py
workers/tests/integrationtests/test_cli_geojson_io.py
workers/tests/integrationtests/test_oqt.py
workers/tests/unittests/test_api_request_models.py
workers/tests/unittests/test_helper.py
workers/tests/unittests/test_load_metadata.py
workers/tests/unittests/test_report_test_report.py

Rename Minimal Test Report to Minimal. This change is consistent to #341 
find . -type f -exec sed -i 's/minimal_test_report/minimal/g' {} +
find . -type f -exec sed -i 's/MinimalTestReport/Minimal/g' {} +
None
- None

test: rename Minimal Test Report to Minimal

---

CHANGELOG.md
docker-compose.development.yml

Mount configuration directory as volume in docker-compose file for development.
- None
~- [ ] My code follows the [style guide](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#pre-commit) before committing~

mount config dir as volume in docker-compose file

---

CHANGELOG.md
workers/ohsome_quality_analyst/indicators/currentness/indicator.py

Fix colorization of red patches in plot creation. Add class assignment for classes 3 and 4.
Closes #437 
- None

fix: plot patches colorization and class assignment of currentness indicator

---

CHANGELOG.md
workers/ohsome_quality_analyst/ohsome/layer_definitions.yaml

fix: wrong ratio_filter

---

website/website/about.html

Fix about page styling.
None
None

fix about page styling

---

CHANGELOG.md
workers/ohsome_quality_analyst/__init__.py
workers/pyproject.toml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_indicator.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_indicator_geojson_io.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_report.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_api_report_geojson_io.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_cli_geojson_io.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_geodatabase.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_building_completeness.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_currentness.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_ghs_pop_comparison_buildings.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_ghs_pop_comparison_roads.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_mapping_saturation.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_poi_density.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_tags_ratio.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_ohsome_client.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_oqt.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_oqt_geojson_io.yaml

Release 0.14.0

---

CHANGELOG.md
workers/ohsome_quality_analyst/base/layer.py
workers/ohsome_quality_analyst/ohsome/layer_definitions.yaml
workers/tests/unittests/test_layer.py
workers/tests/unittests/test_load_layers.py

Add a tag 'namespace' to the layers, which shows to which project it belongs or if it's a core layer.
Closes #
- None

add tag namespace to layers

---

workers/ohsome_quality_analyst/reports/sketchmap_fitness/metadata.yaml

Correct typos in the sketch map fitness report.
-
-
- ~My code follows the [style guide](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#pre-commit) before committing~
- ~I have commented my code~
- ~I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-analyst/blob/main/docs/development_setup.md#tests)~
- ~I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CHANGELOG.md)~

Update workers/ohsome_quality_analyst/reports/sketchmap_fitness/metadata.yaml: Correct typos

---

CHANGELOG.md
workers/ohsome_quality_analyst/__init__.py
workers/pyproject.toml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_cli.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_cli_geojson_io.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_geodatabase.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_attribute_completeness.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_building_completeness.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_currentness.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_minimal.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_indicator_poi_density.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_mapping_saturation.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_oqt.yaml
workers/tests/integrationtests/fixtures/vcr_cassettes/test_oqt_geojson_io.yaml

Release Notes for 0.14.2
None
None

Release 0.14.2

---

CHANGELOG.md
workers/ohsome_quality_analyst/topics/presets.yaml

fix(topic): doctors topic uses the correct healthcare filter

---

CHANGELOG.md
workers/ohsome_quality_analyst/api/api.py
workers/ohsome_quality_analyst/api/request_models.py
workers/ohsome_quality_analyst/api/response_models.py
workers/ohsome_quality_analyst/projects/definitions.py
workers/ohsome_quality_analyst/projects/models.py
workers/ohsome_quality_analyst/projects/projects.yaml
workers/tests/conftest.py
workers/tests/integrationtests/api/conftest.py
workers/tests/integrationtests/api/test_metadata.py
workers/tests/integrationtests/api/test_metadata_projects.py
workers/tests/unittests/api/test_response_models.py
workers/tests/unittests/test_project.py
workers/tests/unittests/test_project_definitions.py

* Add projects as separate model with name and description.
* Add projects to metadata requests.
None
None

Add project models

---

workers/ohsome_quality_analyst/reports/food_related_report/report.py

fix typo that made the report unusable
None
None

fix(food-related-report): fix typo in indicator topic definition

---

workers/ohsome_quality_analyst/indicators/base.py
workers/ohsome_quality_analyst/utils/helper.py

feat(api): add missing metadata to indicator resp

---

CHANGELOG.md
workers/ohsome_quality_analyst/api/api.py

fix(swagger-ui): fix openapi.json to use the given root-path

fix(swagger-ui): fix openapi.json to use the given root-path

---

ohsome_quality_analyst/indicators/attribute_completeness/indicator.py
ohsome_quality_analyst/indicators/base.py
ohsome_quality_analyst/indicators/building_completeness/indicator.py
ohsome_quality_analyst/indicators/currentness/indicator.py
ohsome_quality_analyst/indicators/density/indicator.py
ohsome_quality_analyst/indicators/mapping_saturation/indicator.py
ohsome_quality_analyst/indicators/models.py
ohsome_quality_analyst/reports/models.py
tests/integrationtests/api/response_schema.py
tests/integrationtests/api/test_indicators_mapping_saturation_data.py
tests/integrationtests/indicators/test_attribute_completeness.py
tests/integrationtests/indicators/test_building_completeness.py
tests/integrationtests/indicators/test_currentness.py
tests/integrationtests/indicators/test_density.py
tests/integrationtests/indicators/test_mapping_saturation.py
tests/integrationtests/indicators/test_minimal.py
tests/integrationtests/test_base_indicator.py
tests/integrationtests/test_base_report.py
tests/unittests/test_report_building_report.py
tests/unittests/test_report_food_related_report.py
tests/unittests/test_report_map_action_poc.py
tests/unittests/test_report_minimal.py
tests/unittests/test_report_multilevel_currentness.py
tests/unittests/test_report_multilevel_mapping_saturation.py
tests/unittests/test_report_road_report.py
tests/unittests/test_report_sketchmap_fitness.py

refactor: remove svg figures from indicator result

---

CHANGELOG.md
ohsome_quality_analyst/api/api.py
ohsome_quality_analyst/api/response_models.py
tests/integrationtests/api/test_metadata.py

refactor(api): exclude reports endpoint from schema

---

docs/api.md

Links the blog post on how to visualize OQT API Responses in QGIS in the api.md docs file
Closes #646 
- None
- ~My code follows the [style guide](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-analyst/blob/main/CONTRIBUTING.md#pre-commit) before committing~
- ~I have commented my code~
- ~I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-analyst/blob/main/docs/development_setup.md#tests)~

link blog post on how to visualize OQT API Responses in QGIS

---

ohsome_quality_analyst/api/api.py
ohsome_quality_analyst/reports/sketchmap_fitness/report.py

mapping-saturation-data: rename results to result

---

tests/integrationtests/api/test_indicators_mapping_saturation_data.py

fix: bug in response schema test

---

ohsome_quality_analyst/oqt.py

feat: remove size limitation for currentness indicator

---

ohsome_quality_api/definitions.py
ohsome_quality_api/indicators/currentness/indicator.py
ohsome_quality_api/indicators/mapping_saturation/indicator.py
tests/integrationtests/indicators/test_currentness.py

feat(figures): colors based on semantic UI CSS
Related https://github.com/GIScience/ohsome-quality-api/issues/591

feat(figures): colors based on semantic UI CSS

---

ohsome_quality_api/topics/presets.yaml

feat(topic): add industrial landuse

---

ohsome_quality_api/indicators/building_comparison/indicator.py

fix/building-comparison): errors in description with minor edge cases

---

CHANGELOG.md
ohsome_quality_api/api/api.py
ohsome_quality_api/geodatabase/client.py
ohsome_quality_api/geodatabase/select_eubucco_coverage.sql
ohsome_quality_api/indicators/base.py
ohsome_quality_api/indicators/building_comparison/indicator.py
ohsome_quality_api/indicators/definitions.py
tests/integrationtests/test_base_indicator.py
tests/unittests/test_indicators_definitions.py

feat(indicators): add inverse parameter to coverage function and add inversed eubucco coverage

---

CHANGELOG.md
ohsome_quality_api/indicators/building_comparison/indicator.py
ohsome_quality_api/indicators/building_comparison/metadata.yaml
tests/integrationtests/indicators/test_building_comparison.py

Add feedback to result figure and description.
Closes #776
- None

Building comparison figure improvment

---

CHANGELOG.md
ohsome_quality_api/attributes/attributes.yaml
ohsome_quality_api/indicators/currentness/thresholds.yaml
ohsome_quality_api/reports/remote_mapping_level_one/report.py
ohsome_quality_api/reports/road_report/report.py
ohsome_quality_api/reports/sketchmap_fitness/report.py
ohsome_quality_api/topics/presets.yaml
scripts/run_mapping_saturation_models.py
tests/conftest.py
tests/integrationtests/indicators/test_currentness.py

rename  major_roads_length to roads and change filter to highway=* and type:way

---

CHANGELOG.md
ohsome_quality_api/geodatabase/get_matched_roads.sql
tests/integrationtests/indicators/test_road_comparison.py
tests/integrationtests/test_geodatabase.py

Optimize get matched roads query

---

Dockerfile
Jenkinsfile
README.md

Implements the deployment of OQAPI as Docker Image to a Docker Repository
None

Push Docker Image to Repository

---

CHANGELOG.md
ohsome_quality_api/geodatabase/select_building_area.sql

Improving the calculation time for Norway from 4:40 to 3:49 (18.21% improvment)
None
- None

refactor(building-comparison): improve request to database

---

Dockerfile
ohsome_quality_api/indicators/building_comparison/indicator.py
ohsome_quality_api/indicators/currentness/indicator.py
ohsome_quality_api/indicators/minimal/indicator.py
ohsome_quality_api/indicators/road_comparison/indicator.py
ohsome_quality_api/utils/validators.py
sonar-project.properties
tests/conftest.py
tests/integrationtests/api/response_schema.py
tests/integrationtests/api/test_metadata_indicators.py
tests/integrationtests/api/test_report_geojson_io.py
tests/integrationtests/indicators/test_building_comparison.py
tests/integrationtests/indicators/test_road_comparison.py
tests/integrationtests/test_base_indicator.py
tests/integrationtests/test_geodatabase.py

refactor: fix sonar issues

---

docs/development_setup.md

docs: add information about approvaltests

---

ohsome_quality_api/attributes/attributes.yaml

Fix typos in attributes
None
None
- ~[ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-api/blob/main/docs/development_setup.md#tests)~
- ~[ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/ohsome-quality-api/blob/main/CHANGELOG.md)~

fix typo in attributes.yaml

---

CHANGELOG.md
ohsome_quality_api/indicators/indicators.yaml
ohsome_quality_api/projects/projects.yaml
ohsome_quality_api/topics/presets.yaml
tests/integrationtests/api/conftest.py

This PR adds the topics required for the UNICEF Project as described in issue #832 and implements the new project. All required updates as assignments of topics to the indicators or updating the relevant tests are done as well.
Closes #832 
-

Adding UNICEF topics

---

CHANGELOG.md
ohsome_quality_api/__init__.py
pyproject.toml

This PR is used for the Oqapi release process.

release new version 1.8.0

---

CHANGELOG.md
ohsome_quality_api/indicators/indicators.yaml

This PR includes the  indicator for `attribute-completeness` in the core profile.
Closes #856 
- ~I have commented my code~
- ~I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-api/blob/main/docs/development_setup.md#tests)~

include indicator for attribute-completeness in core profile

---

CHANGELOG.md
ohsome_quality_api/__init__.py
pyproject.toml
scripts/prompt_user_exit_or_continue.sh
scripts/release.sh

This PR is used for the Oqapi release process.

release new version 1.8.1

---

ohsome_quality_api/attributes/attributes.yaml

fix:added subkeys to attribute filters

---

docker-compose.yml
docs/development_setup.md
poetry.lock
pyproject.toml

Overhaul dev docs

---

Jenkinsfile

Added a step to the Jenkinsfile to automatically start the test deploy job.
None
None
- ~[ ] My code follows the [style guide](https://github.com/GIScience/ohsome-quality-api/blob/main/CONTRIBUTING.md#style-guide) and was checked with [pre-commit](https://github.com/GIScience/ohsome-quality-api/blob/main/CONTRIBUTING.md#pre-commit) before committing~
- ~[ ] I have added sufficient unit and integration [tests](https://github.com/GIScience/ohsome-quality-api/blob/main/docs/development_setup.md#tests)~
- ~[ ] I have added new Hurl regression tests and checked all existing [tests](https://github.com/GIScience/ohsome-quality-api/blob/main/re …

build(ci): trigger a deploy of the test API after a successful build

---

CHANGELOG.md
ohsome_quality_api/indicators/land_cover_thematic_accuracy/indicator.py

fix: use math.isclose for approximate testing

---

CHANGELOG.md
ohsome_quality_api/indicators/land_cover_thematic_accuracy/indicator.py
tests/approvals/integrationtests/indicators/test_land_cover_thematic_accuracy.py-test_figure_multi_class.approved.json
tests/approvals/integrationtests/indicators/test_land_cover_thematic_accuracy.py-test_figure_single_class.approved.json

feat: add timestamps to result figure
